
#Les commentaires dans un Makefile debutent par un #


#ici on viens creer un fichier "mon_fichier.txt" avec le texte "Hello world". Il n'y a pas de dependances
mon_fichier.txt :
	echo "Hello world" > mon_fichier.txt

#Ici on lance en ligne de commande 
# $echo "Hello world" => echo est une commande qui affiche ce qui suit dans le buffer de sortie
# La commande "> mon_fichier.txt" viens dirigier cette sortie dans le fichier mon_fichier.txt


#Question:
# Lancez la commande make dans ce repertoire. Observez la creation du fichier texte.
# Relancez make, qu'observez vous?
