
#Verification des dependances

copie_du_fichier.txt: fichier_original.txt
	cp fichier_original.txt copie_du_fichier.txt

#Question
#Analysez ce Makefile, que doit realiser cette commande?
#Lancez make, que ce passe t-il?
#Creez "fichier_original.txt". Inserez y un texte.
#Relancez make. Verifiez le resultat obtenu.
#Supprimez "fichier_original.txt" et relancez make. Qu'obtenez vous?
#Modifiez le contenu de "fichier_original.txt" et sauvegardez. Relancez ensuite make, le resultat final prend-il en compte ce changement?
