
#Il est possible d'enchainer plusieurs commandes:


mon_fichier.txt:
	echo "Bonjour a tous, voici la date: " > mon_fichier.txt
	date >> mon_fichier.txt
	echo "Fin de fichier" >> mon_fichier.txt

#La commande "date" permet d'afficher la date. Celle-ci est concatenee dans mon_fichier.txt

#Question:
#Observez la creation de mon_fichier.txt
#Que contient ce fichier?
#Relancez make, que ce passe t-il?
#Supprimez mon_fichier.txt, et relancez make. Que ce passe t-il?
