#Makefile avec variable

MA_VARIABLE_1="Je suis une variable"
MA_VARIABLE_2=5

sortie.txt:
	#MA_VARIABLE_1=${MA_VARIABLE_1}
	echo ${MA_VARIABLE_1} > sortie.txt
	#MA_VARIABLE_2=${MA_VARIABLE_2}
	echo ${MA_VARIABLE_2} >> sortie.txt

#Question:
#Lancez make, qu'observez-vous.
#Sachant que la syntaxe ${VARIABLE} permet d'acceder au contenu d'une variable, expliquez le fonctionnement de ce script.
