#Question
# Creez le Makefile repondant aux criteres suivants:
# * L'appel a "$make" permet de generer un executable du nom de "mon_executable"
# * L'appel a "$make preprocesseur" permet de generer les fichiers:
#     vecteur_2d.i, vecteur_3d.i et programme_principal.i contenant le resultat du passage du preprocesseur
# * L'appel a "$make assembleur" permet de generer les fichiers:
#     vecteur_2d.s, vecteur_3d.s et programme_principal.s contenant le code assembleur lie a ces meme fichiers.
# * L'appel a "$make clean" permet de supprimer l'ensemble de ces fichiers temporaires et ne garde que le code source et le Makefile.








